import { readFileSync, writeFileSync } from 'node:fs'

const [, , inPath, outPath] = process.argv
if (!inPath || !outPath) {
    console.error('usage: node tools/gen-guests.mjs <in.csv> <out.gs>')
    process.exit(1)
}

const rows = readFileSync(inPath, 'utf8').split(/\r?\n/).slice(1) // drop header
const groups = {}

for (const row of rows) {
    if (!row.trim()) continue
    const [group, first, last] = row.split(',').map(s => (s ?? '').trim())
    if (!group) continue // separator row
    ;(groups[group] ??= []).push({ first, last, slot: first === '' && last === '' })
}

const out = `// GENERATED by tools/gen-guests.mjs from RSVP_list.csv — do not edit by hand.\n` +
    `const GUESTS = ${JSON.stringify(groups, null, 2)}\n`
writeFileSync(outPath, out)
console.log(`Wrote ${Object.keys(groups).length} groups to ${outPath}`)
